### ISSUE TITLE
Module 1: Portfolio application deploy

### ISSUE THREAD

**Issue by ikennarichard** [ikennarichard/my-portfolio#7]
## Module 1 (Week 3): Portfolio application deploy
I initially deployed the project, you will find it at the Live Demo section of the README file.
### Portfolio Site
https://ikennarichard.github.io/my-portfolio/

**Comment by aamirkhan2478** [comment]
Hi @ikennarichard , 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Good descriptive PR :+1: 
✅ Work live demo :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
